apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: readonly-app
  namespace: spinnaker-poc
  labels:
    applicationName: readonly-app
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: readonly-app
  template:
    metadata:
      labels:
        applicationName: readonly-app
    spec:
      containers:
        - name: primary
          image: 477288082536.dkr.ecr.eu-west-1.amazonaws.com/nginx-hello-world
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
